-- Question: <THE QUESTION THE SQL ANSWERS>
-- Description: <DESCRIPTION OF THE SQL>
-- Explanation: <EXPLANATION OF THE SQL (OPTIONAL, YOU CAN OMMIT THIS FIELD)>

-- SQL
SELECT
  *
FROM
  `SOME_DATASASET.SOME_TABLE`;
