version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgresql+asyncpg://local:local@db:5432/local
    volumes:
      - $HOME/.config/gcloud:/root/.config/gcloud
      - "./src:/home/app/src"
    ports:
      - "80:80"

  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.1
    volumes:
      - $HOME/.config/gcloud/application_default_credentials.json:/path/to/service-account-key.json
    ports:
      - "127.0.0.1:5434:5432"
    command: --address 0.0.0.0 --port 5432 --auto-iam-authn --credentials-file /path/to/service-account-key.json data-insights-experimentation:europe-west2:chat-analytics-dev
