version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=local-docker
    volumes:
      - $HOME/.config/gcloud:/root/.config/gcloud
      - "./src:/home/app/src"
    ports:
      - "80:80"
