GCP_PROJECT = "data-insights-experimentation"
GA4_PROJECT = "ga4-analytics-352613"
DATASET = "flattened_dataset"
SQLALCHEMY_URL = f"bigquery://{GA4_PROJECT}/{DATASET}"
TABLE_NAME = "flattened_daily_ga_data_"
